# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('middle_name', models.CharField(blank=True, max_length=45)),
                ('bio', models.CharField(blank=True, max_length=1000)),
                ('email', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('image', models.TextField(blank=True)),
                ('edition', models.CharField(blank=True, max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'managed': False,
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='BooksHasAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'books_has_author',
            },
        ),
        migrations.CreateModel(
            name='BooksHasCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'books_has_category',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'cart_item',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'managed': False,
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_payment', models.DecimalField(decimal_places=0, max_digits=10)),
                ('date_paid', models.DateTimeField()),
                ('credit_card_number', models.CharField(max_length=100)),
                ('cardholder_name', models.CharField(blank=True, max_length=100)),
                ('cardholder_billing_address', models.CharField(blank=True, max_length=1000)),
                ('cardholder_expiration', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'managed': False,
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'shopping_cart',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=45)),
                ('last_name', models.CharField(blank=True, max_length=45)),
                ('middle_name', models.CharField(blank=True, max_length=45)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=40)),
                ('create_time', models.DateTimeField()),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'user',
            },
        ),
    ]
