# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('image', models.TextField(blank=True)),
                ('edition', models.CharField(blank=True, max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'managed': False,
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='BookHasAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'books_has_author',
            },
        ),
        migrations.CreateModel(
            name='BookHasCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'books_has_category',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_payment', models.DecimalField(decimal_places=0, max_digits=10)),
                ('date_paid', models.DateTimeField()),
                ('credit_card_number', models.CharField(max_length=100)),
                ('cardholder_name', models.CharField(blank=True, max_length=100)),
                ('cardholder_billing_address', models.CharField(blank=True, max_length=1000)),
                ('cardholder_expiration', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'payments',
            },
        ),
    ]
