# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0008_auto_20151212_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
    ]
